//! Explorer Tweaks Module

use crate::modules::types::{
    RegistryValue, Tweak, TweakCategory, TweakCheck, TweakOperation, TweakType, WarningLevel,
};

pub fn get_explorer_tweaks() -> Vec<Tweak> {
    vec![
        // Existing tweaks...
        Tweak {
            id: "interface_show_file_extensions".to_string(),
            category: TweakCategory::InterfaceUx,
            name: "Show File Extensions".to_string(),
            description: "Shows file extensions in File Explorer (e.g. .exe, .txt).".to_string(),
            warning_level: WarningLevel::Safe,
            requires_restart: false,
            tweak_type: TweakType::Toggle,
            enabled: false,
            check: Some(TweakCheck::Registry {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "HideFileExt".to_string(),
                expected_value: RegistryValue::DWord(0),
            }),
            revert_operations: Some(vec![TweakOperation::RegistrySet {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "HideFileExt".to_string(),
                value: RegistryValue::DWord(1),
            }]),
            operations: vec![TweakOperation::RegistrySet {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "HideFileExt".to_string(),
                value: RegistryValue::DWord(0),
            }],
        },
        Tweak {
            id: "interface_compact_mode".to_string(),
            category: TweakCategory::InterfaceUx,
            name: "Enable Compact Mode".to_string(),
            description: "Reduces padding between items in File Explorer.".to_string(),
            warning_level: WarningLevel::Safe,
            requires_restart: false,
            tweak_type: TweakType::Toggle,
            enabled: false,
            check: Some(TweakCheck::Registry {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "UseCompactMode".to_string(),
                expected_value: RegistryValue::DWord(1),
            }),
            revert_operations: Some(vec![
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"
                        .to_string(),
                    key: "UseCompactMode".to_string(),
                    value: RegistryValue::DWord(0),
                },
                TweakOperation::Command {
                    cmd: "cmd".to_string(),
                    args: vec![
                        "/c".to_string(),
                        "start".to_string(),
                        "explorer.exe".to_string(),
                    ],
                },
            ]),
            operations: vec![
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"
                        .to_string(),
                    key: "UseCompactMode".to_string(),
                    value: RegistryValue::DWord(1),
                },
                TweakOperation::Command {
                    cmd: "cmd".to_string(),
                    args: vec![
                        "/c".to_string(),
                        "start".to_string(),
                        "explorer.exe".to_string(),
                    ],
                },
            ],
        },
        Tweak {
            id: "interface_show_hidden_files".to_string(),
            category: TweakCategory::InterfaceUx,
            name: "Show Hidden Files".to_string(),
            description: "Shows hidden files and folders in File Explorer.".to_string(),
            warning_level: WarningLevel::Safe,
            requires_restart: false,
            tweak_type: TweakType::Toggle,
            enabled: false,
            check: Some(TweakCheck::Registry {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "Hidden".to_string(),
                expected_value: RegistryValue::DWord(1),
            }),
            revert_operations: Some(vec![TweakOperation::RegistrySet {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "Hidden".to_string(),
                value: RegistryValue::DWord(2),
            }]),
            operations: vec![TweakOperation::RegistrySet {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "Hidden".to_string(),
                value: RegistryValue::DWord(1),
            }],
        },
        Tweak {
            id: "interface_show_system_files".to_string(),
            category: TweakCategory::InterfaceUx,
            name: "Show System Files".to_string(),
            description:
                "Shows protected operating system files. WARNING: Modification can break Windows."
                    .to_string(),
            warning_level: WarningLevel::Careful,
            requires_restart: false,
            tweak_type: TweakType::Toggle,
            enabled: false,
            check: Some(TweakCheck::Registry {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "ShowSuperHidden".to_string(),
                expected_value: RegistryValue::DWord(1),
            }),
            revert_operations: Some(vec![TweakOperation::RegistrySet {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "ShowSuperHidden".to_string(),
                value: RegistryValue::DWord(0),
            }]),
            operations: vec![TweakOperation::RegistrySet {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "ShowSuperHidden".to_string(),
                value: RegistryValue::DWord(1),
            }],
        },
        // ============================================
        // NEW TWEAKS FROM PART 2
        // ============================================
        Tweak {
            id: "interface_jpeg_quality".to_string(),
            category: TweakCategory::InterfaceUx,
            name: "Wallpaper Quality 100%".to_string(),
            description: "Prevents Windows from compressing JPEG desktop wallpapers. Forces maximum image quality.".to_string(),
            warning_level: WarningLevel::Safe,
            requires_restart: false,
            tweak_type: TweakType::Toggle,
            enabled: false,
            check: Some(TweakCheck::Registry {
                root_key: "HKCU".to_string(),
                path: r"Control Panel\Desktop".to_string(),
                key: "JPEGImportQuality".to_string(),
                expected_value: RegistryValue::DWord(100),
            }),
            revert_operations: Some(vec![TweakOperation::RegistryDelete {
                root_key: "HKCU".to_string(),
                path: r"Control Panel\Desktop".to_string(),
                key: "JPEGImportQuality".to_string(),
            }]),
            operations: vec![TweakOperation::RegistrySet {
                root_key: "HKCU".to_string(),
                path: r"Control Panel\Desktop".to_string(),
                key: "JPEGImportQuality".to_string(),
                value: RegistryValue::DWord(100),
            }],
        },
        Tweak {
            id: "interface_remove_home_namespace".to_string(),
            category: TweakCategory::InterfaceUx,
            name: "Remove Home from File Explorer".to_string(),
            description: "Removes the Home section from the File Explorer sidebar, leaving only This PC and real drives.".to_string(),
            warning_level: WarningLevel::Safe,
            requires_restart: false,
            tweak_type: TweakType::Toggle,
            enabled: false,
            check: Some(TweakCheck::RegistryKeyAbsent {
                root_key: "HKLM".to_string(),
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\{f874310e-b6b7-47dc-bc84-b9e6b38f5903}".to_string(),
            }),
            revert_operations: Some(vec![TweakOperation::RegistrySet {
                root_key: "HKLM".to_string(),
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\{f874310e-b6b7-47dc-bc84-b9e6b38f5903}".to_string(),
                key: "".to_string(),
                value: RegistryValue::String("Home".to_string()),
            }]),
            operations: vec![TweakOperation::Command {
                cmd: "reg".to_string(),
                args: vec![
                    "delete".to_string(),
                    r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\{f874310e-b6b7-47dc-bc84-b9e6b38f5903}".to_string(),
                    "/f".to_string(),
                ],
            }],
        },
        Tweak {
            id: "interface_menu_show_delay".to_string(),
            category: TweakCategory::InterfaceUx,
            name: "Instant Menus (Zero Delay)".to_string(),
            description: "Sets menu popup delay to 0ms and tooltip hover time to 20ms for instant UI response.".to_string(),
            warning_level: WarningLevel::Safe,
            requires_restart: false,
            tweak_type: TweakType::Toggle,
            enabled: false,
            check: Some(TweakCheck::Registry {
                root_key: "HKCU".to_string(),
                path: r"Control Panel\Desktop".to_string(),
                key: "MenuShowDelay".to_string(),
                expected_value: RegistryValue::String("0".to_string()),
            }),
            revert_operations: Some(vec![
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"Control Panel\Desktop".to_string(),
                    key: "MenuShowDelay".to_string(),
                    value: RegistryValue::String("400".to_string()),
                },
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"Control Panel\Desktop".to_string(),
                    key: "MouseHoverTime".to_string(),
                    value: RegistryValue::String("400".to_string()),
                },
            ]),
            operations: vec![
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"Control Panel\Desktop".to_string(),
                    key: "MenuShowDelay".to_string(),
                    value: RegistryValue::String("0".to_string()),
                },
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"Control Panel\Desktop".to_string(),
                    key: "MouseHoverTime".to_string(),
                    value: RegistryValue::String("20".to_string()),
                },
            ],
        },
        Tweak {
            id: "interface_launch_to_this_pc".to_string(),
            category: TweakCategory::InterfaceUx,
            name: "Open Explorer to This PC".to_string(),
            description: "Opens File Explorer directly to This PC instead of Quick Access or Home.".to_string(),
            warning_level: WarningLevel::Safe,
            requires_restart: false,
            tweak_type: TweakType::Toggle,
            enabled: false,
            check: Some(TweakCheck::Registry {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "LaunchTo".to_string(),
                expected_value: RegistryValue::DWord(1),
            }),
            revert_operations: Some(vec![TweakOperation::RegistryDelete {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "LaunchTo".to_string(),
            }]),
            operations: vec![TweakOperation::RegistrySet {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "LaunchTo".to_string(),
                value: RegistryValue::DWord(1),
            }],
        },
        Tweak {
            id: "interface_icon_cache_size".to_string(),
            category: TweakCategory::InterfaceUx,
            name: "Increase Icon Cache (4MB)".to_string(),
            description: "Increases Explorer's icon cache to 4096 entries. Eliminates stuttering and blank icons when opening large folders.".to_string(),
            warning_level: WarningLevel::Safe,
            requires_restart: false,
            tweak_type: TweakType::Toggle,
            enabled: false,
            check: Some(TweakCheck::Registry {
                root_key: "HKLM".to_string(),
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer".to_string(),
                key: "Max Cached Icons".to_string(),
                expected_value: RegistryValue::String("4096".to_string()),
            }),
            revert_operations: Some(vec![TweakOperation::RegistryDelete {
                root_key: "HKLM".to_string(),
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer".to_string(),
                key: "Max Cached Icons".to_string(),
            }]),
            operations: vec![TweakOperation::RegistrySet {
                root_key: "HKLM".to_string(),
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer".to_string(),
                key: "Max Cached Icons".to_string(),
                value: RegistryValue::String("4096".to_string()),
            }],
        },
        Tweak {
            id: "interface_context_menu_multi_fix".to_string(),
            category: TweakCategory::InterfaceUx,
            name: "Fix Context Menu for Multiple Files".to_string(),
            description: "Raises the multi-file context menu threshold from 15 to 100. Prevents menu items from disappearing when selecting many files.".to_string(),
            warning_level: WarningLevel::Safe,
            requires_restart: false,
            tweak_type: TweakType::Toggle,
            enabled: false,
            check: Some(TweakCheck::Registry {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer".to_string(),
                key: "MultipleInvokePromptMinimum".to_string(),
                expected_value: RegistryValue::DWord(100),
            }),
            revert_operations: Some(vec![TweakOperation::RegistryDelete {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer".to_string(),
                key: "MultipleInvokePromptMinimum".to_string(),
            }]),
            operations: vec![TweakOperation::RegistrySet {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer".to_string(),
                key: "MultipleInvokePromptMinimum".to_string(),
                value: RegistryValue::DWord(100),
            }],
        },
        Tweak {
            id: "interface_auto_end_tasks".to_string(),
            category: TweakCategory::InterfaceUx,
            name: "Fast Shutdown (Auto End Tasks)".to_string(),
            description: "Forces Windows to automatically kill unresponsive apps on shutdown instead of waiting. Reduces shutdown time from 20s to under 3s.".to_string(),
            warning_level: WarningLevel::Safe,
            requires_restart: false,
            tweak_type: TweakType::Toggle,
            enabled: false,
            check: Some(TweakCheck::Registry {
                root_key: "HKCU".to_string(),
                path: r"Control Panel\Desktop".to_string(),
                key: "AutoEndTasks".to_string(),
                expected_value: RegistryValue::String("1".to_string()),
            }),
            revert_operations: Some(vec![
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"Control Panel\Desktop".to_string(),
                    key: "AutoEndTasks".to_string(),
                    value: RegistryValue::String("0".to_string()),
                },
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"Control Panel\Desktop".to_string(),
                    key: "HungAppTimeout".to_string(),
                    value: RegistryValue::String("5000".to_string()),
                },
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"Control Panel\Desktop".to_string(),
                    key: "WaitToKillAppTimeout".to_string(),
                    value: RegistryValue::String("20000".to_string()),
                },
                TweakOperation::RegistrySet {
                    root_key: "HKLM".to_string(),
                    path: r"SYSTEM\CurrentControlSet\Control".to_string(),
                    key: "WaitToKillServiceTimeout".to_string(),
                    value: RegistryValue::String("5000".to_string()),
                },
            ]),
            operations: vec![
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"Control Panel\Desktop".to_string(),
                    key: "AutoEndTasks".to_string(),
                    value: RegistryValue::String("1".to_string()),
                },
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"Control Panel\Desktop".to_string(),
                    key: "HungAppTimeout".to_string(),
                    value: RegistryValue::String("2000".to_string()),
                },
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"Control Panel\Desktop".to_string(),
                    key: "WaitToKillAppTimeout".to_string(),
                    value: RegistryValue::String("2000".to_string()),
                },
                TweakOperation::RegistrySet {
                    root_key: "HKLM".to_string(),
                    path: r"SYSTEM\CurrentControlSet\Control".to_string(),
                    key: "WaitToKillServiceTimeout".to_string(),
                    value: RegistryValue::String("2000".to_string()),
                },
            ],
        },
        Tweak {
            id: "interface_disable_aero_shake".to_string(),
            category: TweakCategory::InterfaceUx,
            name: "Disable Aero Shake".to_string(),
            description: "Disables the Aero Shake feature that minimizes all windows when you shake one window with the mouse.".to_string(),
            warning_level: WarningLevel::Safe,
            requires_restart: false,
            tweak_type: TweakType::Toggle,
            enabled: false,
            check: Some(TweakCheck::Registry {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "DisallowShaking".to_string(),
                expected_value: RegistryValue::DWord(1),
            }),
            revert_operations: Some(vec![TweakOperation::RegistryDelete {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "DisallowShaking".to_string(),
            }]),
            operations: vec![TweakOperation::RegistrySet {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "DisallowShaking".to_string(),
                value: RegistryValue::DWord(1),
            }],
        },
        Tweak {
            id: "interface_show_seconds_clock".to_string(),
            category: TweakCategory::InterfaceUx,
            name: "Show Seconds in System Clock".to_string(),
            description: "Displays seconds in the taskbar system clock.".to_string(),
            warning_level: WarningLevel::Safe,
            requires_restart: false,
            tweak_type: TweakType::Toggle,
            enabled: false,
            check: Some(TweakCheck::Registry {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "ShowSecondsInSystemClock".to_string(),
                expected_value: RegistryValue::DWord(1),
            }),
            revert_operations: Some(vec![TweakOperation::RegistrySet {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "ShowSecondsInSystemClock".to_string(),
                value: RegistryValue::DWord(0),
            }]),
            operations: vec![TweakOperation::RegistrySet {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "ShowSecondsInSystemClock".to_string(),
                value: RegistryValue::DWord(1),
            }],
        },
        Tweak {
            id: "interface_enthusiast_mode".to_string(),
            category: TweakCategory::InterfaceUx,
            name: "Detailed File Transfer Info".to_string(),
            description: "Forces Windows to always show the speed graph and exact byte counts during file copy/move operations.".to_string(),
            warning_level: WarningLevel::Safe,
            requires_restart: false,
            tweak_type: TweakType::Toggle,
            enabled: false,
            check: Some(TweakCheck::Registry {
                root_key: "HKCU".to_string(),
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\OperationStatusManager".to_string(),
                key: "EnthusiastMode".to_string(),
                expected_value: RegistryValue::DWord(1),
            }),
            revert_operations: Some(vec![TweakOperation::RegistrySet {
                root_key: "HKCU".to_string(),
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\OperationStatusManager".to_string(),
                key: "EnthusiastMode".to_string(),
                value: RegistryValue::DWord(0),
            }]),
            operations: vec![TweakOperation::RegistrySet {
                root_key: "HKCU".to_string(),
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\OperationStatusManager".to_string(),
                key: "EnthusiastMode".to_string(),
                value: RegistryValue::DWord(1),
            }],
        },
        Tweak {
            id: "interface_disable_dynamic_lighting".to_string(),
            category: TweakCategory::InterfaceUx,
            name: "Disable Windows Dynamic Lighting".to_string(),
            description: "Disables the native RGB control system introduced in Windows 11 23H2 that conflicts with iCUE, OpenRGB, and Armoury Crate.".to_string(),
            warning_level: WarningLevel::Safe,
            requires_restart: false,
            tweak_type: TweakType::Toggle,
            enabled: false,
            check: Some(TweakCheck::Registry {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Lighting".to_string(),
                key: "AmbientLightingEnabled".to_string(),
                expected_value: RegistryValue::DWord(0),
            }),
            revert_operations: Some(vec![TweakOperation::RegistrySet {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Lighting".to_string(),
                key: "AmbientLightingEnabled".to_string(),
                value: RegistryValue::DWord(1),
            }]),
            operations: vec![TweakOperation::RegistrySet {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Lighting".to_string(),
                key: "AmbientLightingEnabled".to_string(),
                value: RegistryValue::DWord(0),
            }],
        },
        Tweak {
            id: "interface_disable_autocorrect".to_string(),
            category: TweakCategory::InterfaceUx,
            name: "Disable Autocorrect & Spellcheck".to_string(),
            description: "Disables system-wide autocorrect, double-tap space, and spellchecking. Prevents unexpected popups and lag when pressing unusual key combinations in games.".to_string(),
            warning_level: WarningLevel::Safe,
            requires_restart: false,
            tweak_type: TweakType::Toggle,
            enabled: false,
            check: Some(TweakCheck::Registry {
                root_key: "HKCU".to_string(),
                path: r"SOFTWARE\Microsoft\TabletTip\1.7".to_string(),
                key: "EnableAutocorrection".to_string(),
                expected_value: RegistryValue::DWord(0),
            }),
            revert_operations: Some(vec![
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"SOFTWARE\Microsoft\TabletTip\1.7".to_string(),
                    key: "EnableAutocorrection".to_string(),
                    value: RegistryValue::DWord(1),
                },
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"SOFTWARE\Microsoft\TabletTip\1.7".to_string(),
                    key: "EnableDoubleTapSpace".to_string(),
                    value: RegistryValue::DWord(1),
                },
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"SOFTWARE\Microsoft\TabletTip\1.7".to_string(),
                    key: "EnableSpellchecking".to_string(),
                    value: RegistryValue::DWord(1),
                },
            ]),
            operations: vec![
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"SOFTWARE\Microsoft\TabletTip\1.7".to_string(),
                    key: "EnableAutocorrection".to_string(),
                    value: RegistryValue::DWord(0),
                },
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"SOFTWARE\Microsoft\TabletTip\1.7".to_string(),
                    key: "EnableDoubleTapSpace".to_string(),
                    value: RegistryValue::DWord(0),
                },
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"SOFTWARE\Microsoft\TabletTip\1.7".to_string(),
                    key: "EnableSpellchecking".to_string(),
                    value: RegistryValue::DWord(0),
                },
            ],
        },
        Tweak {
            id: "interface_no_resolve_links".to_string(),
            category: TweakCategory::InterfaceUx,
            name: "Disable Broken Shortcut Search".to_string(),
            description: "Prevents Explorer from freezing while searching for broken shortcuts pointing to disconnected network drives or removed disks.".to_string(),
            warning_level: WarningLevel::Safe,
            requires_restart: false,
            tweak_type: TweakType::Toggle,
            enabled: false,
            check: Some(TweakCheck::Registry {
                root_key: "HKCU".to_string(),
                path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                key: "NoResolveSearch".to_string(),
                expected_value: RegistryValue::DWord(1),
            }),
            revert_operations: Some(vec![
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                    key: "NoResolveSearch".to_string(),
                    value: RegistryValue::DWord(0),
                },
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                    key: "NoResolveTrack".to_string(),
                    value: RegistryValue::DWord(0),
                },
            ]),
            operations: vec![
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                    key: "NoResolveSearch".to_string(),
                    value: RegistryValue::DWord(1),
                },
                TweakOperation::RegistrySet {
                    root_key: "HKCU".to_string(),
                    path: r"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced".to_string(),
                    key: "NoResolveTrack".to_string(),
                    value: RegistryValue::DWord(1),
                },
            ],
        },
        Tweak {
            id: "interface_printscreen_disable_snipping".to_string(),
            category: TweakCategory::InterfaceUx,
            name: "Free PrintScreen Key".to_string(),
            description: "Disables the automatic redirect of PrintScreen to Snipping Tool. Restores the classic screenshot behavior.".to_string(),
            warning_level: WarningLevel::Safe,
            requires_restart: false,
            tweak_type: TweakType::Toggle,
            enabled: false,
            check: Some(TweakCheck::Registry {
                root_key: "HKCU".to_string(),
                path: r"Control Panel\Keyboard".to_string(),
                key: "PrintScreenKeyForSnippingEnabled".to_string(),
                expected_value: RegistryValue::DWord(0),
            }),
            revert_operations: Some(vec![TweakOperation::RegistrySet {
                root_key: "HKCU".to_string(),
                path: r"Control Panel\Keyboard".to_string(),
                key: "PrintScreenKeyForSnippingEnabled".to_string(),
                value: RegistryValue::DWord(1),
            }]),
            operations: vec![TweakOperation::RegistrySet {
                root_key: "HKCU".to_string(),
                path: r"Control Panel\Keyboard".to_string(),
                key: "PrintScreenKeyForSnippingEnabled".to_string(),
                value: RegistryValue::DWord(0),
            }],
        },
    ]
}
